--
  Un-comment only if the Week 02 setup did not work
--

-- USE `databank`;
-- CREATE TABLE IF NOT EXISTS REGIONAL_INVENTORY (
--     INV_ID BIGINT NOT NULL,
--     RETAILER_NAME VARCHAR(100) NOT NULL,
--     CURR_INV_LEVEL BIGINT DEFAULT NULL,
--     REGION VARCHAR(40) NOT NULL,
--     CREATED DATETIME,
--     UPDATED DATETIME,
--     VERSION BIGINT NOT NULL DEFAULT 1,
--     PRIMARY KEY (INV_ID)
-- );
-- INSERT INTO REGIONAL_INVENTORY(INV_ID,RETAILER_NAME,CURR_INV_LEVEL,REGION,CREATED,UPDATED) VALUES (1,'ACME Corp., MD',100,'US',now(),now());
-- INSERT INTO REGIONAL_INVENTORY(INV_ID,RETAILER_NAME,CURR_INV_LEVEL,REGION,CREATED,UPDATED) VALUES (2,'Le Chateau, QC',90,'CA',now(),now());
-- INSERT INTO REGIONAL_INVENTORY(INV_ID,RETAILER_NAME,CURR_INV_LEVEL,REGION,CREATED,UPDATED) VALUES (3,'XYZ Inc., NY',35,'US',now(),now());